const users = [
  {
    name: "Fahim Ahmed",
    profile_photo: './Asset/Img/Fahim Ahmed.jpg',
    post_time_ago: '2 days ago',
    post_text:'Eid Mubarak ❤️❤️',
    post_img: './Asset/Img/post img 1.jpg',
    post_like: '257',
    post_comment: '46',
  },
  {
    name: "Zuma Binte Ziaa",
    profile_photo: './Asset/Img/zuma.jpg',
    post_time_ago: 'a day ago',
    post_text:`Eid pictures 🥰😍❤️😘`,
    post_img: './Asset/Img/post 2.jpg',
    post_like: '52',
    post_comment: '7',
  },
  {
    name: "Sheikh Taniya",
    profile_photo: './Asset/Img/Sheikh.jpg',
    post_time_ago: '13 h',
    post_text:`𝐇𝐚𝐩𝐩𝐲✨ 𝐄𝐢𝐝-𝐮𝐥-𝗔𝗷𝗵𝗮 𝐀𝐧𝐝 𝐄𝐢𝐝 𝐌u𝐛𝐚𝐫𝐚𝐤!💚
    "" ~𝐓𝐚𝐤𝐚𝐛𝐛𝐚𝐥𝐚𝐥𝐥𝐚𝐡𝐮 𝐌𝐢𝐧𝐧𝐚  𝐖𝐚  𝐌𝐢𝐧𝐤𝐮𝐦 !! ✨`,
    post_img: './Asset/Img/post 3.jpg',
    post_like: '50',
    post_comment: '13',
  },
  {
    name: "N.A. Fahim",
    profile_photo: './Asset/Img/N.A fahim.jpg',
    post_time_ago: '8 hours ago',
    post_text:`২০১৯ বিশ্বকাপের স্কোয়াড থেকে বাদ পড়া ছেলেটা আজ দেশ সেরা পেইসার- দ্যা স্পীড স্টার নামে পরিচিত, ২০২৩ বিশ্বকাপে সে ছেলেটা দলে আটো চয়েস ~ তাসকিন আহমেদ।`,
    post_img: './Asset/Img/post 4.jpg',
    post_like: '12',
    post_comment: '4',
  },
  {
    name: "Jahan Rahman Jui",
    profile_photo: './Asset/Img/jahan .jpg',
    post_time_ago: '22 June',
    post_text:`আমি চাই তুমি ভালো থাকো, প্রতিটা মূহুর্ত ভালো কাটুক।`,
    post_img: './Asset/Img/post 5.jpg',
    post_like: '17',
    post_comment: '9',
  },
  {
    name: "Priya Jaigerdar",
    profile_photo: './Asset/Img/Priya.jpg',
    post_time_ago: '5 June',
    post_text:`Happy birthday abbu.l miss you so much.`,
    post_img: './Asset/Img/post 6.jpg',
    post_like: '123',
    post_comment: '41',
  },
  {
    name: "Abul Husen Lalon",
    profile_photo: './Asset/Img/lalon.jpg',
    post_time_ago: 'a day ago',
    post_text:`ঈদের দিন বিকাল বেলা শাহারপাড়া বাজারে এবং রাতে নয়াবন্দর বাজারে আওয়ামিলীগ, যুবলীগ, স্বেচ্ছাসেবক লীগ, ছাত্রলীগ সহ এলাকার মুরব্বিরান ও যুবকদের সাথে শুভেচ্ছা বিনিময়ের সময় মানচেস্টার সিটি আওয়ামিলীগ সভাপতি প্রিয় বড় ভাই অয়েছ কামালী সহ আমরা সবাই আনন্দঘন সময় কাটালাম।`,
    post_img: './Asset/Img/post 8.jpg',
    post_like: '218',
    post_comment: '56',
  },
  {
    name: "Jahan Rahman Jui",
    profile_photo: './Asset/Img/jahan .jpg',
    post_time_ago: '16 h',
    post_text:`🙂🙂🙂`,
    post_img: './Asset/Img/post 7.jpg',
    post_like: '56',
    post_comment: '4',
  },
  {
    name: "Sujel Ahmed",
    profile_photo: './Asset/Img/sujel.jpg',
    post_time_ago: '22 h',
    post_text:`Stay home be safe everyone…`,
    post_img: './Asset/Img/post 9.jpg',
    post_like: '24',
    post_comment: '3',
  },
  {
    name: "Zuma Binte Ziaa",
    profile_photo: './Asset/Img/zuma.jpg',
    post_time_ago: 'a day ago',
    post_text:`🥰😍❤️😘`,
    post_img: './Asset/Img/post 10.jpg',
    post_like: '26',
    post_comment: '5',
  },
];


